apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: ap-south-1

vpc:
  subnets:
    private:
      ap-south-1a: { id: subnet-067d772b252f38adf }
      ap-south-1b: { id: subnet-0f90d5025b33b2d7c }
      ap-south-1c: { id: subnet-0311a3c66081ccf80 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
