name: Python application

on: 
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      continue-on-error: true
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
    - name: Build docker image
      run: |
       docker build . --file Dockerfile --tag suheab/microservices:v1
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
         username: suheab
         password: Asma@786B
    - name: Push docker image to dockerhub
      run: |
        docker push suheab/microservices:v1
        pwd
        ls -la
    - name: Copy deployment and service manifest files to ec2
      uses: tanmancan/action-setup-ssh-agent-key@1.0.0
      with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    - name: Copy deployment and service manifest files to ec2      
      run: |
        scp -T deployment.yml ubuntu@3.109.206.145:/home/ubuntu/sample
    - name: Executing kubectl commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.109.206.145
        username: ubuntu 
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
           cd sample
           cd /home/ubuntu/sample/microservices-in-python
           ls -la
           sudo kubectl get pods -A
           sudo kubectl apply -f deployment.yml
           sudo kubectl apply -f service.yml
           sudo kubectl get services
